"""Fetch, validate, score, and download supporting visuals for a topic."""
from typing import List, Dict, Optional, Iterable
import ipaddress
import json
import os
import re
import shutil
import socket
import subprocess
from urllib.parse import urljoin, urlparse

import requests

from .render_engine import run_ffmpeg


# Candidate media is generated by trusted integrations. Downloads are restricted
# to those hosts so a caller cannot turn the renderer into an arbitrary URL fetcher.
_VISUAL_DOWNLOAD_HOSTS = frozenset(
    {
        "commons.wikimedia.org",
        "upload.wikimedia.org",
        "reddit.com",
        "www.reddit.com",
        "i.redd.it",
        "preview.redd.it",
        "external-preview.redd.it",
        "youtube.com",
        "www.youtube.com",
        "m.youtube.com",
        "youtu.be",
        "i.ytimg.com",
    }
)
_YOUTUBE_HOSTS = frozenset(
    {
        "youtube.com",
        "www.youtube.com",
        "m.youtube.com",
        "youtu.be",
    }
)
_USER_AGENT = "ai-video-factory/1.0"


def _host_matches(host: str, allowed_hosts: Iterable[str]) -> bool:
    normalized = host.lower().rstrip(".")
    return any(
        normalized == allowed or normalized.endswith("." + allowed)
        for allowed in allowed_hosts
    )


def validate_remote_url(
    url: str,
    *,
    allowed_hosts: Optional[Iterable[str]] = _VISUAL_DOWNLOAD_HOSTS,
) -> str:
    """Validate a remote URL before network access.

    HTTPS is required, credentials are rejected, optional host allowlists are
    enforced, and DNS results must resolve only to globally routable addresses.
    """
    if not isinstance(url, str) or not url.strip():
        raise ValueError("remote URL must be a non-empty string")
    parsed = urlparse(url.strip())
    if parsed.scheme.lower() != "https":
        raise ValueError("remote URL must use HTTPS")
    if parsed.username or parsed.password:
        raise ValueError("remote URL credentials are not allowed")
    host = parsed.hostname
    if not host:
        raise ValueError("remote URL must include a hostname")
    host = host.lower().rstrip(".")
    if allowed_hosts is not None and not _host_matches(host, allowed_hosts):
        raise ValueError(f"remote URL host is not allowed: {host}")

    try:
        port = parsed.port or 443
    except ValueError as exc:
        raise ValueError("remote URL has an invalid port") from exc
    if port != 443:
        raise ValueError("remote URL must use HTTPS port 443")

    try:
        addresses = socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
    except socket.gaierror as exc:
        raise ValueError("remote URL hostname could not be resolved") from exc
    for address in addresses:
        try:
            ip = ipaddress.ip_address(address[4][0])
        except ValueError as exc:
            raise ValueError("remote URL resolved to an invalid IP address") from exc
        if not ip.is_global:
            raise ValueError("remote URL resolves to a non-public IP address")
    return url.strip()


def _safe_get(
    url: str,
    *,
    allowed_hosts: Optional[Iterable[str]] = _VISUAL_DOWNLOAD_HOSTS,
    max_redirects: int = 3,
    **kwargs,
):
    """GET a URL while validating every redirect target."""
    current = url
    for _ in range(max_redirects + 1):
        current = validate_remote_url(current, allowed_hosts=allowed_hosts)
        response = requests.get(current, allow_redirects=False, **kwargs)
        if 300 <= response.status_code < 400:
            location = response.headers.get("Location")
            if not location:
                return response
            current = urljoin(current, location)
            continue
        return response
    raise ValueError("too many remote URL redirects")


def _search_wikimedia(topic: str, limit: int = 6) -> List[Dict]:
    """Search Wikimedia Commons for images matching topic."""
    results = []
    try:
        url = "https://commons.wikimedia.org/w/api.php"
        params = {
            "action": "query",
            "format": "json",
            "generator": "search",
            "gsrsearch": topic,
            "gsrlimit": limit,
            "prop": "imageinfo|info",
            "iiprop": "url|extmetadata",
        }
        r = requests.get(url, params=params, timeout=8, headers={"User-Agent": _USER_AGENT})
        if not r.ok:
            return results
        j = r.json()
        pages = j.get("query", {}).get("pages", {})
        for p in pages.values():
            if "imageinfo" in p:
                ii = p["imageinfo"][0]
                src = ii.get("url")
                meta = ii.get("extmetadata", {})
                license_name = meta.get("LicenseShortName", {}).get("value") if meta else None
                title = p.get("title")
                artist = None
                license_url = None
                if meta:
                    artist = meta.get("Artist", {}).get("value") or meta.get("Credit", {}).get("value")
                    license_url = meta.get("LicenseUrl", {}).get("value")
                results.append(
                    {
                        "url": src,
                        "source": "wikimedia",
                        "title": title,
                        "license": license_name,
                        "artist": artist,
                        "license_url": license_url,
                    }
                )
    except Exception:
        return results
    return results


def _search_reddit(topic: str, limit: int = 8) -> List[Dict]:
    """Use Reddit's public search JSON to find image posts related to topic."""
    results = []
    try:
        url = "https://www.reddit.com/search.json"
        params = {"q": topic, "limit": limit, "sort": "relevance"}
        r = requests.get(url, params=params, timeout=8, headers={"User-Agent": _USER_AGENT})
        if not r.ok:
            return results
        j = r.json()
        for item in j.get("data", {}).get("children", []):
            d = item.get("data", {})
            url_candidate = None
            if d.get("preview"):
                images = d["preview"].get("images", [])
                if images:
                    url_candidate = images[0].get("source", {}).get("url")
            if not url_candidate:
                u = d.get("url_overridden_by_dest") or d.get("url")
                if u and re.search(r"\.(jpg|jpeg|png|gif)$", u, flags=re.I):
                    url_candidate = u
            if url_candidate:
                results.append(
                    {
                        "url": url_candidate,
                        "source": "reddit",
                        "title": d.get("title"),
                        "license": "reddit",
                        "subreddit": d.get("subreddit"),
                        "selftext": (d.get("selftext") or "")[:400],
                    }
                )
    except Exception:
        return results
    return results


def _search_youtube(topic: str, limit: int = 6) -> List[Dict]:
    """Use `yt-dlp` with `ytsearch` to find YouTube videos."""
    results = []
    if not shutil.which("yt-dlp"):
        return results
    try:
        query = f"ytsearch{limit}:{topic}"
        proc = subprocess.run(
            ["yt-dlp", "--dump-single-json", query],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if proc.returncode != 0 or not proc.stdout:
            return results
        data = json.loads(proc.stdout)
        entries = data.get("entries") or [data]
        for e in entries[:limit]:
            vid = e.get("id")
            title = e.get("title")
            thumb = e.get("thumbnail")
            url = f"https://www.youtube.com/watch?v={vid}"
            results.append({"url": url, "source": "youtube", "title": title, "thumbnail": thumb})
    except Exception:
        return results
    return results


def _search_youtube_fallback(topic: str, limit: int = 6) -> List[Dict]:
    """Fallback YouTube search by scraping the search results page."""
    results = []
    try:
        q = requests.utils.requote_uri(topic)
        url = f"https://www.youtube.com/results?search_query={q}"
        r = requests.get(url, timeout=8, headers={"User-Agent": _USER_AGENT})
        if not r.ok:
            return results
        text = r.text
        ids = re.findall(r"/watch\?v=([A-Za-z0-9_-]{11})", text)
        seen = []
        for vid in ids:
            if vid in seen:
                continue
            seen.append(vid)
            vurl = f"https://www.youtube.com/watch?v={vid}"
            thumb = f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"
            results.append({"url": vurl, "source": "youtube", "title": "", "thumbnail": thumb})
            if len(results) >= limit:
                break
    except Exception:
        return results
    return results


def _score_and_tag(item: Dict, topic: str) -> Dict:
    """Assign a simple relevance score and a purpose tag based on heuristics."""
    title = (item.get("title") or "").lower()
    score = 0.5
    purpose = "context"
    if any(k in title for k in ("clip", "gameplay", "game", "smp", "minecraft")):
        purpose = "gameplay_clip"
    if any(k in title for k in ("betray", "betrayal", "final", "secret", "reveal", "twist", "climax", "kill", "win", "fail")):
        score += 0.3
        purpose = "conflict"
    if any(k in title for k in ("meme", "funny", "lol", "wtf")):
        score += 0.2
        purpose = "meme"
    if item.get("source") == "wikimedia":
        score += 0.1
        purpose = "context"
    if item.get("source") == "youtube":
        score += 0.2
        purpose = purpose if purpose != "context" else "clip"
    item.update({"score": round(min(1.0, score), 2), "purpose": purpose})
    return item


def annotate_purposes(visuals: List[Dict], summary: Dict) -> List[Dict]:
    """Assign purpose tags for visuals relative to the research summary."""
    if not visuals:
        return visuals
    txt = " ".join(
        [str(summary.get(k, "")) for k in ("who_what", "main_conflict", "strongest_angle")]
    )
    keywords = set(re.findall(r"[A-Za-z]{3,}", txt.lower()))
    beat_keywords = {
        "hook": {"surprise", "shocking", "secret", "never", "first", "didn't"},
        "conflict": {"betray", "attack", "fight", "steal", "exposed", "ruin", "kicked", "ban"},
        "payoff": {"win", "victory", "revealed", "paid off", "success", "revenge"},
        "reaction": {"shocked", "funny", "laugh", "wow", "amazed"},
    }

    out = []
    for v in visuals:
        text_fields = " ".join(
            [str(v.get(k, "")) for k in ("title", "subreddit", "selftext", "description", "url")]
        ).lower()
        match_score = 0
        purpose_hits = {}
        for beat, kws in beat_keywords.items():
            hits = sum(1 for kw in kws if kw in text_fields or kw in keywords)
            if hits:
                purpose_hits[beat] = hits
                match_score += hits
        if purpose_hits:
            chosen = max(purpose_hits.keys(), key=lambda b: purpose_hits[b])
            v["purpose"] = chosen
        v = _score_and_tag(v, summary.get("topic", ""))
        v["match_score"] = min(1.0, 0.1 * match_score + v.get("score", 0))
        out.append(v)
    return out


def vet_with_model(visuals: List[Dict], summary: Dict, api_key: str) -> List[Dict]:
    """Ask an optional model to re-classify visuals by purpose."""
    try:
        from .model_adapter import call_model

        prompt = (
            "You are given a research summary and a list of candidate visuals (url, title, thumbnail, source). "
            "Return a JSON array where each item has keys: url, purpose (one of hook, conflict, payoff, reaction, meme, context, gameplay_clip), confidence (0-1). "
            "Do not include extra text. Research summary:\n"
            + json.dumps(summary)
            + "\nVisuals:\n"
            + json.dumps(visuals)
            + "\n"
        )
        resp = call_model(prompt, api_key)
        if not resp:
            return annotate_purposes(visuals, summary)
        jb = None
        try:
            jb = json.loads(resp)
        except Exception:
            m = re.search(r"(\[\s*\{[\s\S]*\}\s*\])", resp)
            if m:
                try:
                    jb = json.loads(m.group(1))
                except Exception:
                    jb = None
        if not jb or not isinstance(jb, list):
            return annotate_purposes(visuals, summary)
        url_to_v = {v.get("url"): v for v in visuals if v.get("url")}
        out = []
        for item in jb:
            url = item.get("url")
            if not url:
                continue
            base = url_to_v.get(url, {})
            merged = base.copy()
            merged["purpose"] = item.get("purpose") or merged.get("purpose")
            merged["model_confidence"] = float(item.get("confidence") or 0)
            out.append(merged)
        for v in visuals:
            if v.get("url") not in {o.get("url") for o in out}:
                out.append(v)
        return out
    except Exception:
        return annotate_purposes(visuals, summary)


def fetch_visuals(topic: str, max_items: int = 12) -> List[Dict]:
    """Return a scored list of visual candidate dicts for `topic`."""
    items = []
    items.extend(_search_wikimedia(topic, limit=6))
    items.extend(_search_reddit(topic, limit=8))
    yt_items = _search_youtube(topic, limit=6)
    if not yt_items:
        yt_items = _search_youtube_fallback(topic, limit=6)
    items.extend(yt_items)

    scored = [_score_and_tag(it, topic) for it in items]
    seen = set()
    out = []
    for s in sorted(scored, key=lambda x: x.get("score", 0), reverse=True):
        u = s.get("url")
        if not u or u in seen:
            continue
        out.append(s)
        seen.add(u)
        if len(out) >= max_items:
            break
    return out


def _is_meme(item: Dict) -> bool:
    """Lightweight meme/context detection using title/source/subreddit heuristics."""
    title = (item.get("title") or "").lower()
    src = (item.get("source") or "").lower()
    if "meme" in title or "dank" in title or "starterpack" in title:
        return True
    if src == "reddit" and any(
        k in (item.get("subreddit") or "").lower()
        for k in ("memes", "dankmemes", "wholesomememes")
    ):
        return True
    if any(
        pat in title
        for pat in ("when ", "that moment", "mfw", "me when", "pov", "starter pack", "expectation vs reality")
    ):
        return True
    return False


def download_youtube_clip(youtube_url: str, out_dir: str, max_duration: int = 20) -> Dict:
    """Download a short clip from a validated YouTube URL using `yt-dlp` + `ffmpeg`."""
    from datetime import datetime

    youtube_url = validate_remote_url(youtube_url, allowed_hosts=_YOUTUBE_HOSTS)
    if not shutil.which("yt-dlp"):
        return {}
    os.makedirs(out_dir, exist_ok=True)
    try:
        proc = subprocess.run(
            ["yt-dlp", "--dump-single-json", youtube_url],
            capture_output=True,
            text=True,
            timeout=40,
        )
        if proc.returncode != 0 or not proc.stdout:
            return {}
        info = json.loads(proc.stdout)
        video_id = info.get("id")
        if not video_id or not re.fullmatch(r"[A-Za-z0-9_-]{6,32}", str(video_id)):
            return {}
        title = info.get("title")
        uploader = info.get("uploader")
        upload_date = info.get("upload_date")
        tmp_name = os.path.join(out_dir, f"{video_id}.%(ext)s")
        dl = subprocess.run(
            ["yt-dlp", "-f", "bestvideo[ext=mp4]+bestaudio/best", "-o", tmp_name, youtube_url],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if dl.returncode != 0:
            return {}
        downloaded = None
        for f in os.listdir(out_dir):
            if f.startswith(video_id + "."):
                downloaded = os.path.join(out_dir, f)
                break
        if not downloaded:
            for f in os.listdir(out_dir):
                if video_id in f:
                    downloaded = os.path.join(out_dir, f)
                    break
        if not downloaded:
            return {}
        out_clip = os.path.join(out_dir, f"{video_id}_clip_{max_duration}s.mp4")
        if shutil.which("ffmpeg"):
            cmd = [
                "ffmpeg",
                "-y",
                "-i",
                downloaded,
                "-ss",
                "0",
                "-t",
                str(int(max_duration)),
                "-c:v",
                "libx264",
                "-c:a",
                "aac",
                out_clip,
            ]
            try:
                run_ffmpeg(cmd, timeout=120)
            except (OSError, RuntimeError):
                out_clip = downloaded
        else:
            out_clip = downloaded
        thumb = None
        if shutil.which("ffmpeg"):
            thumb_path = os.path.join(out_dir, f"{video_id}_thumb.jpg")
            cmd = ["ffmpeg", "-y", "-i", out_clip, "-ss", "00:00:01", "-vframes", "1", thumb_path]
            try:
                subprocess.run(cmd, capture_output=True, text=True, timeout=20)
                if os.path.exists(thumb_path):
                    thumb = thumb_path
            except Exception:
                thumb = None
        return {
            "local_path": out_clip,
            "thumbnail": thumb,
            "source": "youtube",
            "title": title,
            "uploader": uploader,
            "upload_date": upload_date,
            "url": youtube_url,
        }
    except Exception:
        return {}


def download_visuals(
    visuals: List[Dict],
    out_dir: str,
    download_clips: bool = True,
    clip_max_duration: int = 20,
) -> List[Dict]:
    """Download only approved visual hosts into `out_dir`."""
    from datetime import datetime

    os.makedirs(out_dir, exist_ok=True)
    saved = []
    for i, v in enumerate(visuals):
        try:
            if isinstance(v, dict):
                url = v.get("url")
            else:
                url = v
                v = {"url": url}
            if not url:
                continue
            try:
                parsed = urlparse(validate_remote_url(url, allowed_hosts=_VISUAL_DOWNLOAD_HOSTS))
            except ValueError:
                continue
            host = parsed.hostname or ""
            if _host_matches(host, _YOUTUBE_HOSTS):
                if download_clips:
                    try:
                        meta = download_youtube_clip(url, out_dir, max_duration=clip_max_duration)
                    except ValueError:
                        meta = {}
                    if meta:
                        meta.update(v)
                        meta["downloaded_at"] = datetime.utcnow().isoformat() + "Z"
                        saved.append(meta)
                        continue
                if v.get("thumbnail"):
                    try:
                        r = _safe_get(
                            v["thumbnail"],
                            allowed_hosts=_VISUAL_DOWNLOAD_HOSTS,
                            timeout=12,
                            headers={"User-Agent": _USER_AGENT},
                        )
                        if r.ok and r.content:
                            fn = os.path.join(out_dir, f"thumb_{i+1}.jpg")
                            with open(fn, "wb") as wf:
                                wf.write(r.content)
                            v["local_thumbnail"] = fn
                    except Exception:
                        pass
                v["source"] = v.get("source", "youtube")
                saved.append(v)
                continue
            try:
                r = _safe_get(
                    url,
                    allowed_hosts=_VISUAL_DOWNLOAD_HOSTS,
                    timeout=12,
                    headers={"User-Agent": _USER_AGENT},
                )
                if r.ok and r.content:
                    ext = os.path.splitext(parsed.path)[1]
                    if not ext:
                        ext = ".jpg"
                    if not re.fullmatch(r"\.[A-Za-z0-9]{1,8}", ext):
                        ext = ".jpg"
                    fname = f"img_{i+1}{ext.lower()}"
                    fn = os.path.join(out_dir, fname)
                    with open(fn, "wb") as wf:
                        wf.write(r.content)
                    v["local_path"] = fn
                    v["downloaded_at"] = datetime.utcnow().isoformat() + "Z"
                    if _is_meme(v):
                        v["purpose"] = "meme"
                    saved.append(v)
            except Exception:
                continue
        except Exception:
            continue
    return saved


def prune_visuals(
    visuals: List[Dict],
    min_match_score: float = 0.25,
    min_motion: float = 0.07,
    require_faces_for: List[str] = None,
    min_model_confidence: float = 0.0,
    motion_thresholds: Dict[str, float] = None,
) -> (List[Dict], List[Dict]):
    """Prune visuals by thresholds."""
    if require_faces_for is None:
        require_faces_for = ["hook", "payoff", "conflict"]
    kept = []
    removed = []
    for v in visuals:
        reason = None
        if v.get("match_score", 0) < min_match_score:
            reason = f"low_match_score({v.get('match_score')})"
        purpose = v.get("purpose") or ""
        chosen_motion_threshold = min_motion
        if motion_thresholds and purpose in motion_thresholds:
            try:
                chosen_motion_threshold = float(motion_thresholds.get(purpose))
            except Exception:
                chosen_motion_threshold = min_motion
        motion_val = v.get("motion_score")
        if motion_val is None:
            motion_val = 0.0
        if not reason and motion_val < chosen_motion_threshold:
            reason = f"low_motion({v.get('motion_score')})"
        if not reason and v.get("model_confidence") is not None and v.get("model_confidence", 0) < min_model_confidence:
            reason = f"low_model_confidence({v.get('model_confidence')})"
        if not reason and v.get("purpose") in require_faces_for and v.get("faces_detected", 0) <= 0:
            reason = "no_faces_for_person_purpose"
        if reason:
            r = v.copy()
            r["prune_reason"] = reason
            removed.append(r)
        else:
            kept.append(v)
    return kept, removed
